コンビニ決済の追加に伴ってREADNEを修正
EC-CUBE/sample-payment-plugin pull request #34
Opened 2019-01-11 11:00 UTC by okazy

## 変更内容
- 情報の最新化
- ファイルごとの概要を追加

## 関連
https://github.com/EC-CUBE/sample-payment-plugin/pull/32

2019-01-14 23:26 UTC, chihiro-adachi requested changes

2019-01-14 23:26 UTC, chihiro-adachi commented on README.md
> +{{ include('@SamplePayment/credit_confirm.twig', ignore_missing=true) }}
@okazy ここの記述はあっていますか？

2019-01-15 00:09 UTC, okazy commented on README.md
> +{{ include('@SamplePayment/credit_confirm.twig', ignore_missing=true) }}
@chihiro-adachi 
確認ありがとうございます！
間違っていたため修正しました。
もう一度ご確認をお願いいたします。

2019-01-15 00:10 UTC, chihiro-adachi approved these changes

2019-01-15 00:10 UTC, merged